unittest
MissouriMRR/SUAS-2025 pull request #27
Opened 2024-10-16 00:23 UTC by ouyangyuxuan77

2024-10-31 23:20 UTC, OrangePear13 commented on yolov5n.pt
Delete file.

2024-10-31 23:33 UTC, OrangePear13 commented on test.py
Delete temp test file.

2024-10-31 23:33 UTC, OrangePear13 commented on test2.py
Delete temp test file.

2024-10-31 23:37 UTC, ouyangyuxuan77 commented on test2.py
Hi Nathan

2024-10-31 23:39 UTC, OrangePear13 commented on camera.json
Delete file.

2024-10-31 23:42 UTC, OrangePear13 commented on vision/standard_object/odlc_classify_shape.py
Undo random pointless change.

2024-10-31 23:43 UTC, OrangePear13 commented on vision/unit_tests/photo_model_test.py
Undo random unrelated change

2024-10-31 23:50 UTC, OrangePear13 commented on Unittest_camera_distance.py
Add documentation please.

2024-11-01 00:33 UTC, OrangePear13 commented on Unittest_camera_distance.py
> +        self.assertIsNotNone(result, "Coordinates should not be None")
After checking that a result is not None, it would also be a good idea to explicitly check that the type exactly matches the expected format.

2024-11-01 00:34 UTC, OrangePear13 commented on Unittest_camera_distance.py
> +        if result is not None:  # Check if result is valid before indexing
You already assert that the result is not None, so comparing the result to None again should not be necessary.

2024-11-01 00:34 UTC, OrangePear13 commented on Unittest_camera_distance.py
> +        self.assertIsNotNone(result, "Coordinates should not be None")
Please do this for every test function, for brevity I will not add a comment for each instance.

2024-11-01 00:35 UTC, OrangePear13 commented on Unittest_camera_distance.py
> +        if result is not None:  # Check if result is valid before indexing
Please do this for every test function, for brevity I will not add a comment for each instance.

2024-11-01 00:40 UTC, OrangePear13 commented on Unittest_camera_distance.py
> +            self.assertGreaterEqual(result, 0, "Distance should be non-negative")
Why not test that the calculated distance is correct?

2024-11-01 00:45 UTC, OrangePear13 requested changes
Overall good, just needs documentation. I want to discuss a couple of design choices as well. Just be sure to not accidentally git add everything next time.

2024-11-13 00:09 UTC, ouyangyuxuan77 commented on Unittest_camera_distance.py
ok

2024-11-15 00:49 UTC, OrangePear13 approved these changes
Good job! :D

2024-11-15 00:53 UTC, ouyangyuxuan77 commented
Thank you

Nathan Mejia ***@***.***>于2024年11月14日 周四下午6:50写道：

> ***@***.**** approved this pull request.
>
> Good job! :D
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MissouriMRR/SUAS-2025/pull/27#pullrequestreview-2437463605>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ2Y55DGY2AQLSLPVXDDYXD2AVALZAVCNFSM6AAAAABQAIT26GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMZXGQ3DGNRQGU>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-11-15 01:17 UTC, merged