Added airsim flag and slightly updated poetry file
MissouriMRR/SUAS-2025 pull request #39
Opened 2024-11-08 00:19 UTC by mathdude283

Added airsim flag (hopefully) everywhere there was a sim flag. Called by passing in -a in contrast to -s or --airsim in contrast to --sim. Also updated comments along with this. Also slightly changed poetry file.

2024-11-22 01:30 UTC, DJDMVP commented
Add in the camera changes into the comments and title of the pull request

2025-03-07 19:28 UTC, DJDMVP commented on flight/test_files/suas_test.py
> +async def move_to(
Remove this function and it will solve one of your precommit errors

2025-03-07 19:29 UTC, DJDMVP commented on flight/test_files/connection_test.py
> +    if sim:
This shouldn't be duplicated

2025-03-07 20:01 UTC, DJDMVP reviewed
You have some issues from merging

2025-03-07 20:01 UTC, DJDMVP commented on flight/test_files/suas_test.py
> +async def move_to(
You are importing the correct move to later in the file anyway

2025-03-07 20:01 UTC, DJDMVP commented on flight/test_files/connection_test.py
> +AIRSIM_ADDR: str = "udp://:14030"  # Address to connect to the airsim simulator
This is different from the one in drone.py which is correct

2025-03-07 20:01 UTC, DJDMVP commented on flight/test_files/state_machine_test.py
> +AIRSIM_ADDR: str = "udp://:14030"  # Address to connect to the airsim simulator
This is different from the one in drone.py which is correct

2025-03-07 20:01 UTC, DJDMVP commented on flight/test_files/suas_readiness_test.py
> +AIRSIM_ADDR: str = "udp://:14030"
This is different from the one in drone.py which is correct

2025-03-07 20:01 UTC, DJDMVP commented on flight/test_files/suas_test.py
> +AIRSIM_ADDR: str = "udp://:14030"
This is different from the one in drone.py which is correct

2025-03-07 20:01 UTC, DJDMVP commented on state_machine/drone.py
> +        """
Add the parameter in doc string

2025-03-07 20:01 UTC, DJDMVP commented on state_machine/drone.py
> +        """
also the parameter isn't used

2025-03-07 20:01 UTC, DJDMVP commented on flight/camera.py
This file is a mess why is there a Camera, Camera IRL, and Camera Airsim class

2025-03-20 23:16 UTC, DJDMVP requested changes
Has this been tested in both airsim and ardupilot simulator to verify that it works

2025-03-20 23:16 UTC, DJDMVP commented on vision/common/constants.py
> +
These should no longer be here and are no longer used. Everything is in the camera config file now

2025-03-20 23:16 UTC, DJDMVP commented on state_machine/states/impl/mapping_impl.py
> +        camera: CameraIRL = CameraIRL()
will this not cause problems in unreal

2025-03-20 23:16 UTC, DJDMVP commented on flight/test_files/suas_test.py
> +CON_ADDR: str = "serial:///dev/ttyFTDI:921600"
Shouldn't be needed

2025-03-20 23:16 UTC, DJDMVP commented on flight/test_files/suas_readiness_test.py
> +CON_ADDR: str = "serial:///dev/ttyFTDI:921600"
Shouldn't be needed

2025-03-20 23:16 UTC, DJDMVP commented on flight/test_files/camera_unit_test.py
> +    camera: CameraIRL = CameraIRL()
Could be nice implementing this with airsim as well up to yall

2025-03-20 23:16 UTC, DJDMVP commented on flight/data/waypoint_data.json
I would rather not have any changes to this file especially if they were just work arounds for the simulator

2025-03-20 23:16 UTC, DJDMVP commented on flight/camera.py
> +from vision.common.constants import SENSOR_WIDTH
This should be removed since it is no longer used

2025-03-20 23:16 UTC, DJDMVP commented on flight/camera.py
> +            The yaw in which the camera should point, in degrees (0 is north, 90 is west).
remove from docstring if it is not a parameter

2025-03-20 23:16 UTC, DJDMVP commented on flight/camera.py
> +            The yaw in which the camera should point, in degrees (0 is north, 90 is west).
Remove from docstring if not a parameter

2025-03-20 23:16 UTC, DJDMVP commented on dronekit-2.9.2-py310-none-any.whl
This file should not be added to the repo

2025-03-20 23:56 UTC, mathdude283 commented on dronekit-2.9.2-py310-none-any.whl
This has been removed now

2025-03-20 23:56 UTC, mathdude283 commented on flight/camera.py
> +            The yaw in which the camera should point, in degrees (0 is north, 90 is west).
This has been removed

2025-03-20 23:57 UTC, mathdude283 commented on flight/camera.py
> +            The yaw in which the camera should point, in degrees (0 is north, 90 is west).
This has been removed now

2025-03-20 23:57 UTC, mathdude283 commented on flight/camera.py
> +from vision.common.constants import SENSOR_WIDTH
This has been removed now

2025-03-20 23:57 UTC, mathdude283 commented on flight/data/waypoint_data.json
The changes have been reverted

2025-03-20 23:57 UTC, mathdude283 commented on flight/test_files/camera_unit_test.py
> +    camera: CameraIRL = CameraIRL()
We do not need this at the moment

2025-03-20 23:57 UTC, mathdude283 commented on flight/test_files/suas_readiness_test.py
> +CON_ADDR: str = "serial:///dev/ttyFTDI:921600"
This has been removed

2025-03-20 23:57 UTC, mathdude283 commented on flight/test_files/suas_test.py
> +CON_ADDR: str = "serial:///dev/ttyFTDI:921600"
This has been removed

2025-03-20 23:58 UTC, mathdude283 commented on state_machine/states/impl/mapping_impl.py
> +        camera: CameraIRL = CameraIRL()
This has been fixed

2025-03-20 23:58 UTC, mathdude283 commented on vision/common/constants.py
> +
This has been removed

2025-04-01 23:58 UTC, DJDMVP approved these changes
Looks good glad it works in both 💻 🔥

2025-04-01 23:58 UTC, merged